### ISSUE TITLE
Chose Team Picker not working on Android

### ISSUE THREAD

**Issue by blopeep** [RangerRick/blobile#12]
Running v 1.1.4, build 25 (fd15f670).

Attempting to use the picker for favorite team results in an empty picker.  Only displayed options are:

"Choose your team" (greyed out)
"Cancel"

**Comment by RangerRick** [comment]
Can you try leaving the app up for a little while and then restarting and see if the newer build fixes it?  I did some improvements to the backend non-stream database calls (like the one that grabs team info) since build 25.

It should update without having to get a new build from the store.

**Comment by RangerRick** [comment]
I *think* this was fixed in the process of fixing other things.  Let me know if you still see it.
