### ISSUE TITLE
Tacos abbreviated 

### ISSUE THREAD

**Issue by Mrgio12** [RangerRick/blobile#74]
The Tacos abbreviation when you open a game log of theirs still says LATA
Instead of UTA

Love the app. Keep up the good work

**Comment by RangerRick** [comment]
The abbreviations are actually what comes, officially, from blaseball.com's API  :D

SIBR is currently in the process of collecting a set of improved abbreviations to suggest to The Game Band so we can standardize on a better set, but for now I'm loathe to change it.

**Comment by RangerRick** [comment]
Also _technically_ it's still an unlimited number of LAs, so it's not wrong, per se.  But it would more appropriately be LASTA. (\<grin\>)
